<!DOCTYPE html>
<!--[if lt IE 8 ]><html class="no-js lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
    
    	<?php // Meta tags ?>
        <meta charset="utf-8" />
        <?php // Robot crawling (Disabled for anything but production)
        $boilerplate->setRobots(); ?> 
        <meta name="viewport" content="width=device-width">
        <meta name="format-detection" content="telephone=no" />
        

        <?php // Page Info ?>
        <title><?php echo $boilerplate->page['title']; ?></title>
      	<meta name="description" content="<?php echo $boilerplate->page['meta_desc']; ?>" />
        

        <?php // CSS 
        $boilerplate->loadAsset('css'); ?>


        <?php 
        //Very occationally you'll need to include styles
        //specific to the page, within the head. Maybe the background
        //is being generated by PHP. You can pass in 
        //the $_GET['embedded-styles'] from the templates and it is 
        //injected here.
        if(isset($boilerplate->page['embedded_styles'])): ?>

        <style>
            <?php echo $boilerplate->page['embedded_styles']; ?>
        </style>

        <?php endif;?>
        
        
        <?php // JS 
        $boilerplate->loadAsset('js', 'standard', 'head'); ?>
        

        <?php // Font library ?>


        <?php // Favions and touch icons (with Android support) ?>
        <link rel="icon" sizes="192x192" href="<?php echo $boilerplate->host; ?>/touch-icons/touch-icon-192x192.png">
        <link rel="apple-touch-icon-precomposed" sizes="180x180" href="<?php echo $boilerplate->host; ?>/touch-icons/apple-touch-icon-180x180-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="152x152" href="<?php echo $boilerplate->host; ?>/touch-icons/apple-touch-icon-152x152-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="120x120" href="<?php echo $boilerplate->host; ?>/touch-icons/apple-touch-icon-120x120-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="76x76" href="<?php echo $boilerplate->host; ?>/touch-icons/apple-touch-icon-76x76-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="57x57" href="<?php echo $boilerplate->host; ?>/touch-icons/apple-touch-icon-57x57-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="<?php echo $boilerplate->host; ?>/touch-icons/apple-touch-icon-precomposed.png">
        <link rel="shortcut icon" type="image/png" href="<?php echo $boilerplate->host; ?>/favicon.png" />    
        
    </head>
    <body class="<?php echo $boilerplate->page['body_class']; ?>">